# Определение подробного формата логов для отладки

# log_format debug_format '$remote_addr - $remote_user [$time_local] "$request" '
#                        '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
#                        '$request_time $upstream_response_time';
log_format debug_format '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        'host="$host" port="$server_port" '
                        'upstream="$upstream_addr" '
                        'ups_status="$upstream_status" '
                        'ups_time="$upstream_response_time" '
                        'req_time="$request_time"';

log_format fail2ban '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" "$http_user_agent"';


server {
    listen 80;
    server_name api.feedback-app.pp.ua;

    access_log /var/log/nginx/access.api.80.log debug_format;
    error_log /var/log/nginx/error.api.80.log notice;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.feedback-app.pp.ua;

    access_log /var/log/nginx/access.api.443.log debug_format;
    error_log /var/log/nginx/error.api.443.log notice;
    rewrite_log on;

    ssl_certificate /etc/nginx/certs-feedback-app/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs-feedback-app/key.pem;

    location / {
        add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;

        proxy_pass https://backend_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve static QR codes from the backend service
    # Nginx теперь будет обслуживать эти файлы напрямую из смонтированного тома
    location /static/qr/ {
        root /var/www/feedback-app;  # Корневая директория для статических файлов
        try_files $uri $uri/ =404;   # Попытаться отдать файл, иначе 404
        # Опционально: добавить заголовки для кэширования статических файлов
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}