server {
    listen 80;
    server_name app.feedback-app.pp.ua;

    access_log /var/log/nginx/access.app.80.log debug_format;
    error_log /var/log/nginx/error.app.80.log notice;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.feedback-app.pp.ua;

    access_log /var/log/nginx/access.app.443.log debug_format;
    error_log /var/log/nginx/error.app.443.log notice;

    ssl_certificate /etc/nginx/certs-feedback-app/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs-feedback-app/key.pem;

    # Google Digital Asset Links (Android App Links & Credential Sharing)
    location /.well-known/assetlinks.json {
        root /usr/share/nginx/html;
        default_type application/json;
    }

    location / {
        add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;
        
        proxy_pass http://10.0.0.237:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Для стабильности WebSocket соединений
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}